{
 "title": "ib-by-switch-files",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "remote_name",
    "label": "remote_name",
    "query": {
     "query": "label_values(infiniband_link_info_state{job=\"infiniband_exporter\"},remoteName)"
    }
   },
   {
    "name": "remote_port",
    "label": "remote_port",
    "query": {
     "query": "label_values(infiniband_link_info_state{job=\"infiniband_exporter\"},remotePort)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "up",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(infiniband_link_info_state{state=\"ACT\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "down",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(infiniband_link_info_state{state=\"DOWN\",remotePort=~\"^(?:[1-9]|[12][0-9]|3[0-2])$\",remoteName=~\"^[SPAN01]\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Switch Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (remoteGuid) (infiniband_link_info_state{job=\"infiniband_exporter\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max In (Current)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(infiniband_port_rcv_data{job=\"infiniband_exporter\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Out (Current)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(infiniband_port_xmit_data{job=\"infiniband_exporter\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }, "repeat": "hostname" },
  {
   "title": "Rate_RcvData",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "infiniband_port_rcv_data{job=\"infiniband_exporter\",remoteName=~\"$remote_name\",remotePort=~\"$remote_port\"} > 0",
     "legendFormat": "{{component}}::{{remoteName}}::{{remotePort}}< == >{{localName}}"
    }
   ]
  },
  {
   "title": "Rate_XmitData",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "infiniband_port_xmit_data{job=\"infiniband_exporter\",remoteName=~\"$remote_name\",remotePort=~\"$remote_port\"} > 0",
     "legendFormat": "{{component}}::{{remoteName}}::{{remotePort}}< == >{{localName}}"
    }
   ]
  },
  { "title": "Link", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }, "repeat": "hostname" },
  {
   "title": "Link Flaping",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by(remoteName, remotePort) (increase(infiniband_link_down_counter{job=\"infiniband_exporter\",component=\"sw\"}[$__range])\n) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Link Flaping Count",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum by(remoteName, remotePort) (increase(infiniband_link_down_counter{job=\"infiniband_exporter\",component=\"sw\"}[$__range])\n) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Link Down",
   "type": "table",
   "gridPos": { "h": 12, "w": 19, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "infiniband_link_info_state{state=\"DOWN\",remoteName=~\"$remote_name\",remotePort=~\"^(?:[1-9]|[12][0-9]|3[0-2])$\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Abnormal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "SymbolErrors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "infiniband_symbol_error_counter{job=\"infiniband_exporter\",remoteName=~\"$remote_name\",remotePort=~\"$remote_port\"} >0",
     "legendFormat": "{{component}}::{{remoteName}}::{{remotePort}}< == >{{localName}}"
    }
   ]
  },
  {
   "title": "SymbolErrors",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "infiniband_symbol_error_counter{job=\"infiniband_exporter\",remoteName=~\"$remote_name\",remotePort=~\"$remote_port\"} > 0",
     "legendFormat": "{{component}}::{{remoteName}}::{{remotePort}}< == >{{localName}}"
    }
   ]
  },
  {
   "title": "PhysicalErrors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "increase(infiniband_port_local_physical_errors{job=\"infiniband_exporter\",remoteName=~\"$remote_name\",remotePort=~\"$remote_port\"}[$__range]) > 0",
     "legendFormat": "{{component}}::{{remoteName}}::{{remotePort}}< == >{{localName}}"
    }
   ]
  },
  {
   "title": "PhysicalErrors",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "increase(infiniband_port_local_physical_errors{job=\"infiniband_exporter\",remoteName=~\"$remote_name\",remotePort=~\"$remote_port\"}[$__range]) > 0",
     "legendFormat": "{{component}}::{{remoteName}}::{{remotePort}}< == >{{localName}}"
    }
   ]
  },
  {
   "title": "PortRcvSwitchRelayErrors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "increase(infiniband_port_rcv_switch_relay_errors{job=\"infiniband_exporter\",remoteName=~\"$remote_name\",remotePort=~\"$remote_port\"}[$__range]) > 0",
     "legendFormat": "{{component}}::{{remoteName}}::{{remotePort}}< == >{{localName}}"
    }
   ]
  },
  {
   "title": "PortRcvSwitchRelayErrors",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "increase(infiniband_port_rcv_switch_relay_errors{job=\"infiniband_exporter\",remoteName=~\"$remote_name\",remotePort=~\"$remote_port\"}[$__range]) > 0",
     "legendFormat": "{{component}}::{{remoteName}}::{{remotePort}}< == >{{localName}}"
    }
   ]
  },
  {
   "title": "RcvRemotePhysicalErrors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "increase(infiniband_port_rcv_remote_physical_errors{job=\"infiniband_exporter\",remoteName=~\"$remote_name\",remotePort=~\"$remote_port\"}[$__range]) > 0",
     "legendFormat": "{{component}}::{{remoteName}}::{{remotePort}}< == >{{localName}}"
    }
   ]
  },
  {
   "title": "RcvRemotePhysicalErrors",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "increase(infiniband_port_rcv_remote_physical_errors{job=\"infiniband_exporter\",remoteName=~\"$remote_name\",remotePort=~\"$remote_port\"}[$__range]) > 0",
     "legendFormat": "{{component}}::{{remoteName}}::{{remotePort}}< == >{{localName}}"
    }
   ]
  },
  {
   "title": "RcvErrors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "increase(infiniband_port_rcv_errors{job=\"infiniband_exporter\",remoteName=~\"$remote_name\",remotePort=~\"$remote_port\"}[$__range]) > 0",
     "legendFormat": "{{component}}::{{remoteName}}::{{remotePort}}< == >{{localName}}"
    }
   ]
  },
  {
   "title": "RcvErrors",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "increase(infiniband_port_rcv_errors{job=\"infiniband_exporter\",remoteName=~\"$remote_name\",remotePort=~\"$remote_port\"}[$__range]) > 0",
     "legendFormat": "{{component}}::{{remoteName}}::{{remotePort}}< == >{{localName}}"
    }
   ]
  },
  {
   "title": "XmitDiscards",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "increase(infiniband_port_xmit_discard{job=\"infiniband_exporter\",remoteName=~\"$remote_name\",remotePort=~\"$remote_port\"}[$__range]) > 0",
     "legendFormat": "{{component}}::{{remoteName}}::{{remotePort}}< == >{{localName}}"
    }
   ]
  },
  {
   "title": "XmitDiscards",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "targets": [
    {
     "expr": "increase(infiniband_port_xmit_discard{job=\"infiniband_exporter\",remoteName=~\"$remote_name\",remotePort=~\"$remote_port\"}[$__range]) > 0",
     "legendFormat": "{{component}}::{{remoteName}}::{{remotePort}}< == >{{localName}}"
    }
   ]
  },
  {
   "title": "IB_Port_NeighborMTUDiscards",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "increase(infiniband_port_neighbor_mtu_discards{job=\"infiniband_exporter\",remoteName=~\"$remote_name\",remotePort=~\"$remote_port\"}[$__range]) > 0",
     "legendFormat": "{{component}}::{{remoteName}}::{{remotePort}}< == >{{localName}}"
    }
   ]
  },
  {
   "title": "InactivedDiscards",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "targets": [
    {
     "expr": "increase(infiniband_port_inactive_discards{job=\"infiniband_exporter\",remoteName=~\"$remote_name\",remotePort=~\"$remote_port\"}[$__range]) > 0",
     "legendFormat": "{{component}}::{{remoteName}}::{{remotePort}}< == >{{localName}}"
    }
   ]
  },
  {
   "title": "InactivedDiscards",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "targets": [
    {
     "expr": "increase(infiniband_port_inactive_discards{job=\"infiniband_exporter\",remoteName=~\"$remote_name\",remotePort=~\"$remote_port\"}[$__range]) > 0",
     "legendFormat": "{{component}}::{{remoteName}}::{{remotePort}}< == >{{localName}}"
    }
   ]
  },
  {
   "title": "BufferOverRunErrors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "targets": [
    {
     "expr": "increase(infiniband_port_buffer_overrun_errors{job=\"infiniband_exporter\",remoteName=~\"$remote_name\",remotePort=~\"$remote_port\"}[$__range]) > 0",
     "legendFormat": "{{component}}::{{remoteName}}::{{remotePort}}< == >{{localName}}"
    }
   ]
  },
  {
   "title": "BufferOverRunErrors",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "targets": [
    {
     "expr": "increase(infiniband_port_buffer_overrun_errors{job=\"infiniband_exporter\",remoteName=~\"$remote_name\",remotePort=~\"$remote_port\"}[$__range]) > 0",
     "legendFormat": "{{component}}::{{remoteName}}::{{remotePort}}< == >{{localName}}"
    }
   ]
  },
  {
   "title": "LocalLinkIntegrityErrors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "targets": [
    {
     "expr": "increase(infiniband_local_link_integrity_errors{job=\"infiniband_exporter\",remoteName=~\"$remote_name\",remotePort=~\"$remote_port\"}[$__range]) > 0",
     "legendFormat": "{{component}}::{{remoteName}}::{{remotePort}}< == >{{localName}}"
    }
   ]
  },
  {
   "title": "LocalLinkIntegrityErrors",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
   "targets": [
    {
     "expr": "increase(infiniband_local_link_integrity_errors{job=\"infiniband_exporter\",remoteName=~\"$remote_name\",remotePort=~\"$remote_port\"}[$__range]) > 0",
     "legendFormat": "{{component}}::{{remoteName}}::{{remotePort}}< == >{{localName}}"
    }
   ]
  },
  {
   "title": "NeighborMTUDiscards",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "targets": [
    {
     "expr": "increase(infiniband_port_neighbor_mtu_discards{job=\"infiniband_exporter\",remoteName=~\"$remote_name\",remotePort=~\"$remote_port\"}[$__range]) > 0",
     "legendFormat": "{{component}}::{{remoteName}}::{{remotePort}}< == >{{localName}}"
    }
   ]
  },
  {
   "title": "NeighborMTUDiscards",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
   "targets": [
    {
     "expr": "increase(infiniband_port_neighbor_mtu_discards{job=\"infiniband_exporter\",remoteName=~\"$remote_name\",remotePort=~\"$remote_port\"}[$__range]) > 0",
     "legendFormat": "{{component}}::{{remoteName}}::{{remotePort}}< == >{{localName}}"
    }
   ]
  },
  {
   "title": "ExcessiveBufferOverRunErrorsExtended",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
   "targets": [
    {
     "expr": "increase(infiniband_excessive_buffer_overrun_errors_extended{job=\"infiniband_exporter\",remoteName=~\"$remote_name\",remotePort=~\"$remote_port\"}[$__range]) > 0",
     "legendFormat": "{{component}}::{{remoteName}}::{{remotePort}}< == >{{localName}}"
    }
   ]
  },
  {
   "title": "ExcessiveBufferOverRunErrorsExtended",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 121 },
   "targets": [
    {
     "expr": "increase(infiniband_excessive_buffer_overrun_errors_extended{job=\"infiniband_exporter\",remoteName=~\"$remote_name\",remotePort=~\"$remote_port\"}[$__range]) > 0",
     "legendFormat": "{{component}}::{{remoteName}}::{{remotePort}}< == >{{localName}}"
    }
   ]
  },
  {
   "title": "TopkPhysicalErrors(Node-Exporter)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 129 },
   "targets": [
    {
     "expr": "increase(node_infiniband_port_receive_remote_physical_errors_total{job=\"node\",hostname=~\"h4-.*-gpu\"}[$__range]) > 0",
     "legendFormat": "{{hostname}}:{{device}}"
    }
   ]
  }
 ]
}